### PR TITLE
converting specs to the latest RSpec syntax

### PR DESCRIPTION
**Pull request by accessd**

### CODE REVIEW

**Comment by accessd** [comment]
specs fixed:smiley:

**Comment by accessd** [comment]
any chance to get this merged?

**Comment by jipiboily** [comment]
It's July 4th today, so people in the US are out of office today. I am sure @smathieu will look at it when he has some free time :grinning:.

**Comment by accessd** [comment]
ok! :smile:

**Comment by smathieu** [comment]
Sorry, I've been swamped in recent days. I'll try to get this done this week.

**Comment by accessd** [comment]
How about to convert specs? :smiley:

**Comment by smathieu** [comment]
So sorry, I've been super busy lately. I'll add a reminder to my calendar to do this tonight. 

Thanks for the PR, it's very much appreciated.

**Pull request merged**
