### PR TITLE
Ability to use your own layout

### PR DESCRIPTION
**Pull request by accessd**
refs #47

### CODE REVIEW

**Comment by smathieu** [comment]
Thanks for the PR. Will review shortly.

**Comment by smathieu** [comment]
Looks like you broke the specs. Would you mind fixing them?

**Comment by accessd** [comment]
Specs fixed in https://github.com/smathieu/prosperity/pull/50. Associated with an update on RSpec 3.

**Comment by smathieu** [comment]
Ok. PR merged. Sorry for the long delay.

**Comment by accessd** [comment]
Ok! I did rebase this branch from master and specs fixed.

**Comment by smathieu** [comment]
Merged and released a new version with your code. Thanks for PR and sorry it took so long to merge.

**Comment by accessd** [comment]
Ok! Thanks! :+1:

**Pull request merged**
